# Generated by Django 4.0 on 2023-06-23 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.RemoveField(
            model_name='topic',
            name='content',
        ),
    ]
